[pytest]
addopts =
    -v
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure

testpaths = tests
python_files = test_*.py

markers =
    smoke
    sanity
    regression